// <auto-generated />
using System;
using Atmos.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Atmos.Web.Data.Migrations
{
    [DbContext(typeof(AtmosDbContext))]
    partial class AtmosDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Atmos.Web.Data.RecentSearch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<double?>("ElevationMeters")
                        .HasColumnType("float");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("LastAccessedUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<string>("LocationType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValue("Zip");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasColumnType("char(32)");

                    b.Property<string>("Units")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValue("Imperial");

                    b.HasKey("Id");

                    b.HasIndex("SessionId", "Label")
                        .IsUnique();

                    b.HasIndex("SessionId", "LastAccessedUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_RecentSearch_SessionId_LastAccessedUtc");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("SessionId", "LastAccessedUtc"), new[] { "Label", "Latitude", "Longitude", "ElevationMeters", "Units", "LocationType" });

                    b.ToTable("RecentSearch", null, t =>
                        {
                            t.HasCheckConstraint("CK_RecentSearch_Latitude", "[Latitude] BETWEEN -90 AND 90");

                            t.HasCheckConstraint("CK_RecentSearch_Longitude", "[Longitude] BETWEEN -180 AND 180");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
